### ISSUE TITLE
Missing icons...

### ISSUE THREAD

**Issue by danhigham** [splintah/nerdbar.widget#1]
Great widget! However, for me, the icons don't appear and I can't seem to find a way to test the CSS!

**Comment by splintersuidman** [comment]
Have you placed the folder `nerdbar.widget` in your widget folder, or have you placed the contents of the `nerdbar.widget` folder in your widget folder?
You should do the latter.

**Comment by danhigham** [comment]
Perfect! Thanks so much 👍
