### ISSUE TITLE
The widget works fine but the Icons are missing!

### ISSUE THREAD

**Issue by xaleza** [splintah/nerdbar.widget#2]
<img width="1439" alt="captura de ecra 2018-10-11 as 20 52 13" src="https://user-images.githubusercontent.com/32540757/46830089-8cc0c700-cd97-11e8-81c9-be1d661c0330.png">

Please help, I really enjoy the design

**Comment by xaleza** [comment]
OK i fixed it. I had a problem with the Font Awesome.
Just added this code to the widgets folder

`refreshFrequency: false

render: () ->
    return '''
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    '''
`

**Comment by splintersuidman** [comment]
I was just about to comment on this issue: I think the solution would be to copy all the files inside this repository directly into `~/Library/Application\ Support/Übersicht/widgets`, instead of copying the repository itself into that folder.

Since you figured it out, I'll close the issue.
